# =============================================================================
# FITREP Evaluator - Pre-Push Public Repo Cleanup
# =============================================================================
# Purpose: Remove any documents that reference specific tokens, endpoints, or
#          internal incident details before pushing to a public GitHub repo.
#          Run this AFTER phase1-strip.ps1 and phase1b-strip.ps1.
#
# Run from PowerShell at the project root:
#   cd D:\Coding\Fitness-Report-Evaluator
#   .\scripts\pre-push-cleanup.ps1
#
# Preview without deleting:
#   .\scripts\pre-push-cleanup.ps1 -DryRun
# =============================================================================

param(
    [switch]$DryRun = $false,
    [switch]$Force = $false
)

$ErrorActionPreference = "Stop"
$projectRoot = Split-Path -Parent $PSScriptRoot
Set-Location $projectRoot

Write-Host ""
Write-Host "===========================================================" -ForegroundColor Yellow
Write-Host " FITREP EVALUATOR - PRE-PUSH CLEANUP" -ForegroundColor Yellow
Write-Host "===========================================================" -ForegroundColor Yellow
Write-Host ""

if (-not $Force -and -not $DryRun) {
    Write-Host "This script removes documents that contain internal infrastructure" -ForegroundColor Red
    Write-Host "references, token variable names, or detailed defect lists. Required" -ForegroundColor Red
    Write-Host "before pushing to a public GitHub repository." -ForegroundColor Red
    Write-Host ""
    $confirm = Read-Host "Type DELETE to proceed, anything else to abort"
    if ($confirm -ne "DELETE") {
        Write-Host "Aborted by user." -ForegroundColor Yellow
        exit 0
    }
}

function Remove-Target {
    param([string]$Path, [string]$Reason)
    $full = Join-Path $projectRoot $Path
    if (Test-Path $full) {
        if ($DryRun) {
            Write-Host "[DRY] Would remove: $Path  ($Reason)" -ForegroundColor Cyan
        } else {
            Remove-Item -Path $full -Recurse -Force -ErrorAction SilentlyContinue
            Write-Host "[REM] Removed:      $Path  ($Reason)" -ForegroundColor Green
        }
    } else {
        Write-Host "[SKIP] Not present: $Path" -ForegroundColor DarkGray
    }
}

# --- Stale historical docs that reference the prior production deployment ---
Remove-Target -Path "docs\PRD-COMPREHENSIVE-IMPROVEMENTS.md"   -Reason "References Render and Supabase by name"
Remove-Target -Path "docs\IMPLEMENTATION_SUMMARY.md"           -Reason "Describes deleted architecture"
Remove-Target -Path "docs\IMMEDIATE-ACTION-CHECKLIST.md"       -Reason "Contains incident-specific token recovery steps"
Remove-Target -Path "docs\CONFIG.md"                           -Reason "References deleted backend config"
Remove-Target -Path "docs\DATA_STRUCTURE.md"                   -Reason "References FITREP_DATA token variable"
Remove-Target -Path "docs\NETWORK-EFFICIENCY.md"               -Reason "References deleted network cache module"
Remove-Target -Path "docs\UNIFIED-STORAGE.md"                  -Reason "References deleted unified storage module"
Remove-Target -Path "docs\MEMORY-MANAGEMENT.md"                -Reason "References cloud sync patterns"
Remove-Target -Path "docs\PERF-BENCHMARKS.md"                  -Reason "Benchmarks against deleted modules"
Remove-Target -Path "docs\PERFORMANCE-IMPROVEMENTS.md"         -Reason "Performance against deleted modules"
Remove-Target -Path "docs\InstructionsExampleComponent.tsx.txt" -Reason "React migration artifact"
Remove-Target -Path "docs\GLOBALS-MIGRATION.md"                -Reason "Cloud-era migration document"

# --- Trae IDE workspace ---
Remove-Target -Path ".trae"                                    -Reason "Trae IDE workspace, references prior architecture"

# --- Environment file ---
Remove-Target -Path ".env"                                     -Reason "SESSION_SECRET residue, prohibited in PoC mode"
Remove-Target -Path ".env.local"                               -Reason "Local env, if present"
Remove-Target -Path ".env.example"                             -Reason "Example env, if present"

# --- Old node_modules in case it was repopulated by accident ---
Remove-Target -Path "node_modules"                             -Reason "Will be regenerated by npm install if needed"

Write-Host ""
Write-Host "===========================================================" -ForegroundColor Yellow
if ($DryRun) {
    Write-Host " DRY RUN COMPLETE. No files were deleted." -ForegroundColor Cyan
} else {
    Write-Host " PRE-PUSH CLEANUP COMPLETE." -ForegroundColor Green
    Write-Host ""
    Write-Host " Next: initialize git and push." -ForegroundColor White
    Write-Host "   git init" -ForegroundColor Gray
    Write-Host "   git branch -M main" -ForegroundColor Gray
    Write-Host "   git remote add origin https://github.com/furby203824/Fitness-Report-Evaluator.git" -ForegroundColor Gray
    Write-Host "   git add ." -ForegroundColor Gray
    Write-Host "   git commit -m `"Initial commit - PoC realignment v3.0.0`"" -ForegroundColor Gray
    Write-Host "   git push -u origin main" -ForegroundColor Gray
}
Write-Host "===========================================================" -ForegroundColor Yellow
Write-Host ""
